from .solhomeviewmodel import QSolHomeViewModel
from .solimdbviewmodel import QSolImdbViewModel
from .solmoviesviewmodel import QSolMoviesViewModel
from .solshowsviewmodel import QSolShowsViewModel
from .solfilmdetailviewmodel import QSolFilmDetailViewModel
from .solsearchviewmodel import QSolSearchViewModel
